### PR TITLE
Add ngx-markdown

### PR DESCRIPTION
**Pull request by jfcere**
Related to issue https://github.com/jfcere/ngx-markdown/issues/493

- Removed `-rc.x/`-next.x` from angular packages in `package.json` to be compatible with ngx-markdown v16
- Added `ngx-markdown` v16 and `marked` dependencies
- Added `MarkdownModule` configuration to `app.config.ts`
- Added `MarkdownModule` to `AboutCompontent` imports
- Added a transclusion example of `MarkdownComponent` usage in the `AboutComponent`
- Added a remote fetching example of `MarkdownComponent` usage in the `AboutComponent`
- Added `provideClientHydration` in providers to enable hydration functionality in the `app.config.server.ts`

To validate, run the commands below and navigate to the "About" page

```bash
# update npm packages
npm i

#run angular application with ssr
npm run dev:ssr
```

### CODE REVIEW

**Comment by brandonroberts** [comment]
@jfcere what's the purpose of this PR?

**Comment by jfcere** [comment]
> @jfcere what's the purpose of this PR?

Like it is written in the comment of the PR, to help investigate the hydratation issue with ngx-markdown

**Comment by brandonroberts** [comment]
@jfcere ok, but this is a standalone repository that doesn't need or use ngx-markdown. I suggest creating your own repository for this.

**Comment by jfcere** [comment]
This is the repository you provided me to help investigate the issue... remember?

But whatever this was so you can see what changes are needed to integrate ngx-markdown to an SSR project.

I'll close the PR.

**Comment by brandonroberts** [comment]
Ok

**Comment by jfcere** [comment]
@brandonroberts I just realised the issue was not reported by you but somebody else... I don't know why he referred me to your repository.

I am sorry about the misunderstanding.

**Pull request closed without merging**
